{
 "title": "Annes Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" },
   { "name": "emission_factor", "label": "Emission Factor", "query": "0.000310" },
   { "name": "PUE", "label": "Power Usage Effectiveness", "query": "1.135" }
  ]
 },
 "panels": [
  { "title": "mg CO2 per application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Daily Dynamic CO2 emissions (mg) per Namespace",
   "type": "bargauge",
   "description": "The total emission per namespace is calculated by multiplying power consumption with the emission factor and power usage efficiency. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum (increase(kepler_container_joules_total{container_namespace=~\"$namespace\",pod_name=~\"$pod\"}[24h:1m])) * $watt_per_second_to_kWh * $PUE ) * $emission_factor * 1000 * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "( sum by (container_namespace) (increase(kepler_container_joules_total{container_namespace=~\"$namespace\",pod_name=~\"$pod\"}[24h:1m])) * $watt_per_second_to_kWh * $PUE ) * $emission_factor * 1000 * 100",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  },
  {
   "title": "Total Dynamic CO2 emissions per Namespace",
   "type": "timeseries",
   "description": "The total emission per namespace is calculated by multiplying power consumption with emission factor and power usage efficiency. Per minute.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "( sum by (container_namespace) (increase(kepler_container_joules_total{container_namespace=~\"$namespace\",}[1m])) * $watt_per_second_to_kWh * $PUE ) * $emission_factor * 1000 * 100",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  },
  {
   "title": "Dynamic CO2 emissions per Pod",
   "type": "timeseries",
   "description": "The total emission is calculated by multiplying power consumption with the emission factor and power usage efficiency. Value is per minute.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "( sum by (container_namespace,pod_name) (increase(kepler_container_joules_total{container_namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])) * $watt_per_second_to_kWh * $PUE ) * $emission_factor * 1000 * 100",
     "legendFormat": "{{pod_name}} -- {{container_namespace}}"
    }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Dynamic Power Consumption by Namespace (kWh per day)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  increase(\n      (kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (container_namespace) (\n  increase(\n      (kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh ",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  },
  {
   "title": "Total Dynamic Power Consumption (W) per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (container_namespace) (irate(kepler_container_joules_total{container_namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  },
  {
   "title": "Total Dynamic Power Consumption (W) per Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by (container_namespace,pod_name) (irate(kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} -- {{container_namespace}}"
    }
   ]
  }
 ]
}